mysite/blog/urls.py
from django.urls import path, re_path
from . import views
from blog.feeds import LatestPostFeeds

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share', views.post_share, name='post_share'),
    path('feed/', LatestPostFeeds(), name='post_feed'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('blog/', include('blog.urls'), name='blog'),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views')
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='post')

class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('post', 'Post'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)

    status = models.CharField(choices=STATUS_CHOICE, default='draft', max_length=10)

    def __str__(self):
        return self.title

    def absolute_url(self):
        return reverse('blog:post_detail', args=(self.publish.year,
                                            self.publish.strftime("%m"),
                                            self.publish.strftime("%d"),
                                            self.slug)) 

    objects = models.Manager()
    published = PublishedManager()


class Comment(models.Model):
    post = models.ForeignKey("Post", related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    body = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=20)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views import generic
from .forms import EmailPostForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from taggit.models import Tag
# Create your views here.

# class PostListView(generic.ListView):
#     query_set = Post.published.all()
#     template_name = 'blog/list.html'

def post_share(request, post_id):
    post = get_object_or_404(Post, pk=post_id)    
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #发送邮件

            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/share.html', {'post': post, 'form': form, 'sent': sent})

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    return render(request, 'blog/list.html', {'posts': posts,
                                                'page': page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='post',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/detail.html', {'post': post,
                                                 'comments': comments,
                                                 'new_comment': new_comment,
                                                 'comment_form': comment_form,
                                                 })

mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'blog/base.css' %}">
    </head>

    <body>
        <div class="container">
            <div class="content">
                {% block content %}
                {% endblock %}
            </div>
            <div class="slider">
                <h2>My Blog</h2>
                <p>Welcome to my blog.I have written {% total_posts %} posts so far.</p>
                <h3>Latest Post</h3>
                {% latest_posts 3 %}
                <h3>Most commented posts</h3>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                        <li>
                            <a href="{{post.absolute_url}}">{{post.title}}</a>
                        </li>
                    {% endfor %}
                </ul>
                <p><a href="{% url 'blog:post_feed' %}">Click Me to get RSS feed ^_^</a></p>
            </div>
        </div>
    </body>
</html>

mysite/blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}} {% endblock %}

{% block content %}
<h2 class='post_title'>{{post.title}}</h2>
<p class='post_info'>Published {{post.publish}} by {{post.auth}}</p>

<p>{{post.body | markdown}}</p>
<p><a href="{% url 'blog:post_share' post.id %}">Share By Email</a></p>

<h3>Comments</h3>
{% with comments.count as comment_count %}
    {% if comment_count %}
        <p>Have {{comment_count}} comment{{comment_count|pluralize}}.</p>
    {% else %}
        <p>Not have comment yet.</p>
    {% endif %}
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <h3>commnet post by {{comment.name}} at date:{{comment.update}}</h3>
        <p>{{comment.body|linebreaks}}</p>
    </div>
{% endfor %}

{% if new_comment %}
    <p>Commit comment successfully.</p>
{% else %}
    <form action="" method="POST">
        {% csrf_token %}
        {{comment_form.as_p}}
        <input type="submit", value='submit'>
    </form>
{% endif %}

{% endblock %}

mysite/blog/templates/blog/latest_posts.html
<ul>
    {% for post in my_posts %}
        <li>
            {{ forloop.count }}
            <a href="{{ post.absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} My Blog {% endblock %}

{% block content %}

<!-- {% if tag %}
    <h1>Posts selected by tag {{tag}}</h1>
{% endif %} -->

{% for post in posts %}

    <!-- <h2><a href="{% url 'blog:post_detail' year=post.publish.year month=post.publish.month day=post.publish.day post=post.slug %}">{{post.title}}</a></h2> -->
    <h2><a class='post_title' href='{{ post.absolute_url }}'>{{post.title}}</a></h2>
    <!-- <p class="tag">Tag:{{post.tags | join:','}}</p> -->
    <p class='post_info'>Published at {{post.publish}} by {{post.author}}</p>
    <p>{{post.body | markdown | truncatewords_html:30 }}</p>
{% endfor %}

{% with page=posts %}
    {% include "blog/pagination.html" %}
{% endwith %}

{% endblock %}

mysite/blog/templates/blog/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>    

mysite/blog/templates/blog/share.html
{% extends "blog/base.html" %}

{% block title %}
Share Post
{% endblock title %}

{% block content %}
{% if sent %}
    <p>You have share post successfully</p>
{% else %}
    <h1>Share "{{post.title}}" by Email</h1>
    <form action="{% url 'blog:post_share' post.id %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit", value="submit">
    </form>
{% endif %}

{% endblock content %}